version: '3'
services:

  janusz-the-bot:
    build: .
    container_name: "janusz-the-bot"
    image: "janusz-the-bot"
    ports:
      - 80:8080
    environment:
      - MYSQL_URL=mysql://root:password@mysql/janusz
      - HUBOT_SLACK_TOKEN
      - HUBOT_SLACK_VERIFICATION_TOKEN
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - default
    command: --init-file /data/application/init.sql
    volumes:
      - .:/data/application/

networks:
  default:
