# Default values for janusz-the-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: softwaremill/janusz-the-bot
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: sml-docker-hub

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - host: janusz-the-bot.sml.io
      paths: [/status,/slack/actions]
  tls: []
    # - secretName: janusz-the-bot-tls
    #  hosts:
    #  - janusz-the-bot.sml.io

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  imageTag: 5.7.14
  mysqlRootPassword: pass
  mysqlUser: janusz
  mysqlPassword: janusz
  databaseName: janusz
  initializationFiles:
    bob-db.sql: |-
      CREATE DATABASE IF NOT EXISTS janusz DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      USE janusz;
      CREATE TABLE IF NOT EXISTS janusz (id INT,data TEXT, PRIMARY KEY (id));

slack:
  token: 1234566789
  verificationToken: 12345678899
