# Default values for janusz-the-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/sml-gke-iac/janusz-the-bot
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  path: /
  hosts:
    - host: janusz-the-bot.sml.io
      paths: [/status,/slack/actions]
  tls:
    - secretName: janusz-the-bot-tls
      hosts:
        - janusz-the-bot.sml.io

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  mysqlUser: janusz
  mysqlDatabase: janusz

slack:
  # hubot https://softwaremill.slack.com/services/B03JTM099
  # classic app https://api.slack.com/apps/A0156M45HSB
  exitOnDisconnect: true
  apiUrl: "https://softwaremill.slack.com/api"
  logLevel: info

backend:
  fourthQuestionLambdaUrl: "https://amazonaws.com/FourthQuestionApiDeploy/fourth-question"
  grammarStatsAppUrl: "https://janusz-backend.sml.io"
  kudosAppLogin: "SMLKudos"

bitbucket:
  username: "softwaremill"

scalaTimes:
  appUrl: "https://scalatimes.tools.softwaremill.com"

trello:
  board: "51acaaefbeac745c31005966"

imgflipApi:
  username: "JanuszTheBot"

mailgun:
  domain: "sandboxe517492f75f54aab8ffac7c9afb4c3ab.mailgun.org"

sendgrid:
  username: "app22582599@heroku.com"

db:
  hostConfig:
    name: mysql-configuration
    key: DB_HOST
    kind: configMap
  dbNameConfig:
    name: janusz-the-bot-mysql
    key: DB_NAME
    kind: secret
  usernameConfig:
    name: janusz-the-bot-mysql
    key: USERNAME
    kind: secret
  passwordConfig:
    name: janusz-the-bot-mysql
    key: PASSWORD
    kind: secret

appConfigSecret: "{{ .Release.Name }}-secrets"
