apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  MYSQL_URL: mysql://{{ .Values.mysql.mysqlUser }}:{{ .Values.mysql.mysqlPassword }}@{{ include "mysql.fullname" . }}/{{ .Values.mysql.databaseName }}
  HUBOT_SLACK_VERIFICATION_TOKEN: {{ .Values.slack.verificationToken }}
  HUBOT_SLACK_TOKEN: {{ .Values.slack.token }}
