apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
{{- include "janusz-the-bot.labels" . | nindent 4 }}
data:
  MYSQL_URL: mysql://{{ .Values.mysql.mysqlUser }}:{{ .Values.mysql.mysqlPassword }}@{{ include "janusz-the-bot.fullname" . }}-mysql/{{ .Values.mysql.mysqlDatabase }}
  FOURTH_QUESTION_LAMBDA_URL: {{ .Values.backend.fourthQuestionLambdaUrl }}
  HUBOT_BITBUCKET_USERNAME: {{ .Values.bitbucket.username }}
  HUBOT_GRAMMAR_STATS_APP_URL: {{ .Values.backend.grammarStatsAppUrl }}
  HUBOT_KUDOS_APP_LOGIN: {{ .Values.backend.kudosAppLogin }}
  HUBOT_SCALA_TIMES_APP_URL: {{ .Values.scalaTimes.appUrl }}
  HUBOT_SLACK_EXIT_ON_DISCONNECT: {{ .Values.slack.exitOnDisconnect | quote }}
  HUBOT_TRELLO_BOARD: {{ .Values.trello.board }}
  IMGFLIP_API_USERNAME: {{ .Values.imgflipApi.username }}
  MAILGUN_DOMAIN: {{ .Values.mailgun.domain }}
  SENDGRID_USERNAME: {{ .Values.sendgrid.username }}
  SLACK_API_URL: {{ .Values.slack.apiUrl }}
  HUBOT_LOG_LEVEL: {{ .Values.slack.logLevel }}
