apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "janusz-the-bot.fullname" . }}
  labels:
    {{- include "janusz-the-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "janusz-the-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "janusz-the-bot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_URL
              value: "mysql://$MYSQL_USER:$MYSQL_PASS@$MYSQL_HOST/$MYSQL_DB"
            - name: MYSQL_HOST
              valueFrom:
                {{ include "dbHostConfigSource" . }}:
                  key: {{ .Values.db.hostConfig.key }}
                  name: {{ .Values.db.hostConfig.name }}
            - name: MYSQL_DB
              valueFrom:
                {{ include "dbNameConfigSource" . }}:
                  key: {{ .Values.db.dbNameConfig.key }}
                  name: {{ .Values.db.dbNameConfig.name }}
            - name: MYSQL_USER
              valueFrom:
                {{ include "dbUsernameConfigSource" . }}:
                  key: {{ .Values.db.usernameConfig.key }}
                  name: {{ .Values.db.usernameConfig.name }}
            - name: MYSQL_PASS
              valueFrom:
                {{ include "dbPasswordConfigSource" . }}:
                  key: {{ .Values.db.passwordConfig.key }}
                  name: {{ .Values.db.passwordConfig.name }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.appConfigSecret . }}
            - configMapRef:
                name: {{ include "janusz-the-bot.fullname" . }}
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
